#+TITLE: My Firefox Profile
#+AUTHOR: Emermer
The user-overrides.js file in this repo was made to go with [[https://github.com/arkenfox/user.js][arkenfox's user.js file]] and will not work without it. If you are not aware of how the arkenfox configuration works I'd HIGHLY recommend reading the [[https://github.com/arkenfox/user.js/wiki][documentation]] to build some understanding before using my user-overrides.js file. This custom profile also contains steps that allow a custom homepage without using any extensions! If you want to know how to make your own custom html file, I highly recommend watching this [[https://www.youtube.com/watch?v=Hb0p-TxgZzs][video]]! Instruction for setup are listed below!

* Included Add-ons
The following add-ons come out of the box:
- [[https://ublockorigin.com/][Ublock Origin]]
- [[https://universal-bypass.org/][Universal Bypass]]
- [[https://darkreader.org/][Dark Reader]]
- [[https://libredirect.github.io//][LibRedirect]]

* Included Search Engines
The following search engines come out of the box:
- [[https://search.brave.com/][Brave]] @brave (Default)
- [[https://www.youtube.com/][YouTube]] @vd
- [[https://wiki.archlinux.org/][ArchWiki]] @aw

* PROFILE SETUP GUIDE
1. type "about:profiles" into the URL bar in Firefox.
2. Click "Create a New Profile" and complete the "Create Profile Wizard." The name of the profile doesn't matter.
3. Now that the new profile is made, you should first click "Set as default profile" next to the profile you just created. 
4. You should also see two directories. Click the "Open Directory" button next to "Root Directory."
5. Download the contents of this repository, as well as the arkenfox "user.js" file and "update.sh" script onto your system. Close Firefox, delete all files out of the Root Directory, and paste the "user-overrides.js" file, "search.json.mozlz4" file, "extensions" folder, "chrome" folder, as well as the arkenfox "user.js" file and "update.sh" script into the Root Directory of the new profile you just created. 

Now that we've finished the majority of the setup process, you have the option to choose if you do or do not want a custom homepage to finish out the setup!

- choosing this step means that you WANT a custom homepage via the provided "index.html" file or your own if you have one! -
6a. Put the "index.html" file into a safe place on your system. I put mine in the .mozilla/firefox directory and I recommend you to do the same! Use your text editor of choice to open user-overrides.js and change the file directory on line 2 to fit your location path of the "index.html" file. Make sure that you keep the "file://" or else Firefox won't be able to read the directory!

- SKIPPING STEP 6a REQUIRES AN ALTERNATE STEP - DO NOT DO THIS STEP IF YOU'VE DONE STEP 6a! -
6b. Use your text editor of choice to open user-overrides.js and remove lines 1-4 or just comment out lines 2 and 3.

7. Run the "update.sh" script so the "user-overrides.js" file can merge with the arkenfox "user.js" file and update the user.js if there are any new versions.

For the people who followed step 6b, then congrats, your profile is now installed! Enjoy it!!
For the people who followed step 6a, we have just a couple more steps we have to do!

* HOMEPAGE SETUP GUIDE
1. Use your text editor of choice to open the autoconfig.cfg file. You should be able to find a directory starting with the "file://" like we've seen before. All you'll need to do is change it to the location path of your "index.html" file as we've done before in step 6a.
2. Move the "autoconfig.cfg" file into /usr/lib/firefox/ and then move the "autoconfig.js" into /usr/lib/firefox/defaults/pref/.

Now upon relaunching Firefox, you should be very welcomed to see your homepage being occupied by that sweet html file. 
You're done. Enjoy!
